version: '3'

services:
  db:
    image: mysql:8
    env_file:
      - .env
    ports:
      - "3305:3305"
    networks:
      - backend

  app:
    restart: always
    depends_on:
      - db
    links:
      - db
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge

